version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=udemy_node
    ports:
      - '5432:5432'
    volumes:
      - dadosdb:/var/lib/postgresql/data
volumes:
  dadosdb:
    driver: local
